# name-template: "v$RESOLVED_VERSION ğŸŒˆ"
# tag-template: "v$RESOLVED_VERSION"
# categories:
#   - title: "ğŸš€ Features"
#     labels:
#       - "feature"
#       - "enhancement"
#   - title: "ğŸ› Bug Fixes"
#     labels:
#       - "fix"
#       - "bugfix"
#       - "bug"
#   - title: "ğŸ§° Maintenance"
#     label: "chore"
# change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
# change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
# version-resolver:
#   major:
#     labels:
#       - "major"
#   minor:
#     labels:
#       - "minor"
#   patch:
#     labels:
#       - "patch"
#   default: patch
# template: |
#   ## Changes

#   $CHANGES

# autolabeler:
#   - label: "chore"
#     files:
#       - "*.md"
#     branch:
#       - '/docs{0,1}\/.+/'
#   - label: "bug"
#     branch:
#       - '/fix\/.+/'
#     title:
#       - "/fix/i"
#   - label: "enhancement"
#     branch:
#       - '/feature\/.+/'
#     body:
#       - "/JIRA-[0-9]{1,4}/"

# references:
#   - main
#   - release
#   - v.+
name-template: "v$NEXT_MINOR_VERSION"
tag-template: "v$NEXT_MINOR_VERSION"
categories:
  - title: "ğŸš€ Features"
    label: "enhancement"
  - title: "ğŸ› Hotfixes"
    label: "bug"
  - title: "ETC"
    label: "documentation"
change-template: "- $TITLE #$NUMBER @$AUTHOR "
template: |
  ## Uncategorized
  $CHANGES
  ### Bump setup.py version must be included here!
